### ISSUE TITLE
Jedispool on close doesnnot return 

### ISSUE THREAD

**Issue by arvindnr** [xetorthio/jedis#1010]
On request to release the jedis resource the thread stuck on socketRead0. Upon inspection socketInputStream class ,impl.getTimeout() is set to 0 rather 2000 (Default). Sometime is 2000 and some time it 0. When it is 0 it never returns and stuck on socketRead0 (Waiting on jedis to respond).

```
public int read(byte b[], int off, int length) throws IOException {
    return read(b, off, length, impl.getTimeout());
}
```

Jedis Version : 2.7.2
Redis Version: Redis server v=2.8.9 

Stack Frame:
SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) line: not available [native method]
SocketInputStream.socketRead(FileDescriptor, byte[], int, int, int) line: 116  
SocketInputStream.read(byte[], int, int, int) line: 170 
SocketInputStream.read(byte[], int, int) line: 141  
SocketInputStream.read(byte[]) line: 127  
RedisInputStream.ensureFill() line: 195 
RedisInputStream.readByte() line: 40  
Protocol.process(RedisInputStream) line: 132  
Protocol.read(RedisInputStream) line: 196  
Client(Connection).readProtocolWithCheckingBroken() line: 288  
Client(Connection).getAll(int) line: 258  
Client(Connection).getAll() line: 250  
Jedis(BinaryJedis).resetState() line: 1653  
JedisPool.returnResource(Jedis) line: 110  
JedisPool.returnResource(Object) line: 12  
Jedis.close() line: 3306 

Thanks
Arvind Rapaka

**Comment by HeartSaVioR** [comment]
Hi!
First of all, please refer to https://github.com/xetorthio/jedis/issues/1006#issuecomment-109722284 regarding why getAll() blocks or is timed-out.

Jedis changes timeout to infinite when you run these commands - blpop, brpop, brpoplpush, eval, evalsha, subscribe, psubscribe, monitor - and revert timeout when command is executed.

Sharing your codes help us finding actual issue. Thanks!

**Comment by srirama-rayaprolu** [comment]
Hi HeartSaVioR,

In case of server is dead/rebooted while executing this command, whether time out will happen or not? At present the my application thread got stuck'ed on the SOCKET read call and not returning. How to over come this.

Thanks in adavance.

Srirama.

**Comment by marcosnils** [comment]
@srirama-rayaprolu if the server dies or get's rebooted `Jedis` should throw a connection exception as it will probably get a RST TCP. Can you provide a consistent scenario to reproduce this?

**Comment by srirama-rayaprolu** [comment]
@marcosnils Thanks for the reply

I am checking redundancy for my application and configured Redis sentinels. I am doing hard reboot (init 6) and checking whether my application connects to other Redis instance or not. 

I checked the TCP dump and there is no RST signal received. As no RST signal and no time out set for client socket, the socket is not getting closed and no exception is coming. 

Let me know any other details.

**Comment by srirama-rayaprolu** [comment]
There is a work around available for this. 

Thanks for the API setting TCP KEEP ALIVE option enabled on the socket. 
Changed the default KEEP ALIVE time at the OS level and after that able to receive the connection exception and reconnecting to other REDIS server.

The default time out value for TCP KEEP ALIVE in LINUX is 2 hours. There is no option available in JAVA API for setting this value per socket level

**Comment by maheshdatt** [comment]
We are currently hitting this issue in our prod env. Shouldn't we be providing the socket timeout at the connection level instead of relying on the os level setting? 

Is there a reason why we set to infinite for the so timeout for brpop?

**Comment by slavik57** [comment]
We are encountering the same issue (Jedis 2.8) while executing `transaction.exec()`

**Comment by slavik57** [comment]
We figured out why this was happening.

Code example:
```
JedisPubSub listener = ....
try (Jedis jedis = redisConnectionProvider.getConnection) {
  Future<?> future = executorService.submit(() -> {
    jedis.subscribe(listener, channel)
  });

  future.get(timeout, timeUnit)
} finally {
  // do the unsubscribing logic for the listener
 ...
}
```

In our case, we had a thread (A) that used Jedis connection from a pool with `try{}` block.
Inside that block, we created another thread (B) that used the same connection by subscribing to notifications. This thread was blocked inside the `subscribe()` method.
The A thread waited for B thread for some time and got a timeout exception. That led to existing the `try{}` block and returning the connection to the pool.
Inside the finally block we aborted listening to notifications.

The problem was that the connection was already returned to the pool and another thread (C) got it.
Now thread B and C were using the same connection in different places. That made the `pipelinedCommands` inside the `redis.clients.jedis.Connection` to get out of sync, causing the `Connection.getAll()` method to get stuck.
```
public List<Object> getAll(int except) {
    List<Object> all = new ArrayList<Object>();
    flush();
    while (pipelinedCommands > except) {
      try {
        all.add(readProtocolWithCheckingBroken());
      } catch (JedisDataException e) {
        all.add(e);
      }
      pipelinedCommands--;
    }
    return all;
  }
```
It got stuck inside when calling the `readProtocolWithCheckingBroken()`. When debugging I saw that the `pipelineCommands` value was 1 and the `expect` value was also 1. We were inside the while loop. Clearly it couldnt get to that state unless some other thread was messing around with the same connection.
