### ISSUE TITLE
'ERR max number of clients reached' in JedisSentinelPool.initSentinels breaks the pool initialization

### ISSUE THREAD

**Issue by Foxlik** [xetorthio/jedis#1036]
If, during the sentinel initialization, one of the sentinels rejects the connection attempt with 

    redis.clients.jedis.exceptions.JedisDataException: ERR max number of clients reached

the whole pool initialization fails.

It seems, that in the process of sentinel pool initialization, every sentinel is tried, regardless of whether master has been found or not. And, the initialization only catches JedisConnectionException, while `max number of clients reached` throws JedisDataException. So even if one of three sentinels returns this error during initialization, the whole process fails.

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/JedisSentinelPool.java#L145

Changing the catch clause to `JedisException` should fix the problem, but I am not sure that is the right way to fix things.

**Comment by HeartSaVioR** [comment]
@Foxlik 
You found the missed spot! Great!

Btw, maybe we may want to convert ```ERR max number of clients reached``` to JedisConnectionException since Redis will close the socket immediately.
@xetorthio @marcosnils What do you think?

**Comment by marcosnils** [comment]
@HeartSaVioR I guess it makes sense to transform the `max numbers of clients reached` error into a JedisConnectionException as the Jedis instance will become useless because the InputStreams will raise en exception when trying to perform anything.

The only thing that I don't quite like is the fact that we will have to parse the response error message in order transform the JedisDataException into a `JedisConnectionException`. I'm trying to think of a way to do this the most elegant way. 

Any suggestions?

**Comment by HeartSaVioR** [comment]
@marcosnils 
One way I can think is that we can ping immediately when JedisDataException occurs.
But it requires additional operation for each JedisDataException which is definitely trade-off.

**Comment by marcosnils** [comment]
@HeartSaVioR  the idea of  sending "hidden" commands just to check the sanity of the Jedis instance gives me goosebumps :smile: . 

Maybe instead of doing this we can finally start thinking of a proper way to reset a jedis state so it can be reused (reconnect) if a connection error occurs.

**Comment by HeartSaVioR** [comment]
@marcosnils 
Maybe yes.
In fact, there're two different situations about when to reset state.
1. Connection is broken, so we should re-establish connection.
2. Everything is fine but we forgot to clean up (didn't clean up Pipeline or Transaction, etc) so we should clean up before returning instance to the pool without re-establish connection.

We may want to think about what approaches can ensure two situations together.

Btw, this issue is reporting spot from JedisSentinelPool which could stop subscribing from Sentinel when Throwable, but not JedisConnectionException occurred. We have to resolve this first.

**Comment by HeartSaVioR** [comment]
@Foxlik I addressed this to #1080. Please check.
