### ISSUE TITLE
Missing command ROLE

### ISSUE THREAD

**Issue by WhiteTrashLord** [xetorthio/jedis#1124]
I miss the command ROLE in Jedis. Why it's not supported? :)

**Comment by HeartSaVioR** [comment]
@WhiteTrashLord 
Please refer #664.
ROLE provides complex structure, but if Jedis parses them for users, Jedis may be bound with specific Redis version.
So I think we don't need to be in hurry to add ROLE unless many users are requested with their use cases.

**Comment by WhiteTrashLord** [comment]
Sorry, I didn't find the old issue. Is there another solution to find out if the redis instance is a Master or not with Jedis?
The output is indeed a bit complicated. What about returning a JSON ( String ) as return value for the command ROLE?

**Comment by Kiemes** [comment]
Hi @HeartSaVioR. If you are looking for additional use cases, here is a big one. As http://redis.io/topics/sentinel-clients is suggesting the usage of ROLE command in sentinel setups, I guess a lot of people would like to use the feature including me. Otherwise everybody is constructing their own INFO REPLICATION parser. Thanks and best regards, Tom

**Comment by sazzad16** [comment]
Closed in favor of #664
