### ISSUE TITLE
jedis support R/W Splitting?

### ISSUE THREAD

**Issue by liujg** [xetorthio/jedis#1154]
I fould jedis connect to redis-cluster just by master server,it doesnot support R/W Splitting? why? Do u plan to add this feature in future?

**Comment by HeartSaVioR** [comment]
Welcome to open source world!

If some of features are not implemented, there could be various reasons, 

1. author's intention : You can ask the reasons to not adding the feature. But you should ask it from mailing list so other contributors can discuss the benefit. Please refer https://github.com/xetorthio/jedis/blob/master/CONTRIBUTING.md for more details.

2. author doesn't have time to implement : It's time to be a contributor! 
You can request author to implement it, but I don't recommend you to just wait and get. 
Because most OSPs don't get supported by companies which means author maintains the project using his/her leisure time.

We don't have the time to look into #988 which should be resolved before splitting R/W. Personally I don't like accessing slaves because Redis Cluster doesn't do failover slave nodes, but if someone implements it, I'm happy to support it.
