### ISSUE TITLE
Incorporate simple self-loading POJO cache service into Jedis

### ISSUE THREAD

**Issue by bascan** [xetorthio/jedis#1157]
At interact.io we like Jedis a lot and we've written a simple self-loading POJO cache service that covers many of our use cases. We'd like to have such a generic a convenience service incorporated into the Jedis library.

Please take a look at our implementation: https://gist.github.com/bascan/3607126cf8e557d6dc54

Thanks!
Bas Cancrinus - interact.io

**Comment by marcosnils** [comment]
@bascan we appreciate that you like Jedis and we're always welcome to new contributors . We're trying to keep Jedis as small as possible because we're only 3 contributors and we receive a lot of bugs and improvements every week. Because of that, for satellite projects around Jedis we always encourage the community to create a new library and not bundle them into Jedis directly.

The main reason for this is because these projects need to be tested and maintained with the same spirit of Jedis, and we (the current contributors) can't commit to that task as we can barely keep up to date with the current workflow. It's also a better way to manage as end users won't need to wait for a Jedis release in order to get new features.

I'm pretty sure that there are a lot of Jedis users that would benefit from your solution, that's why we hope that you can create a library out of it (maybe sponsored by your company) and generate community around that. If there's anything from the Jedis side that you'd like to propose in order to deliver a better product just let us know. 

Thanks.

**Comment by bascan** [comment]
@marcosnils Thanks for your comprehensive reply! I factored our cache service out into the following public github repo: https://github.com/bascan/jedis-pojo

I'll release a Maven artifact from this repo in a few days. Could you add a reference to jedis-pojo in your wiki so your users can find us?

Thanks, Bas

**Comment by marcosnils** [comment]
@bascan amazing!. I'll add the link to the wiki shortly.
