### ISSUE TITLE
About Resharding

### ISSUE THREAD

**Issue by zhengfc** [xetorthio/jedis#1160]
Is JedisCluster provide the resharding function like redis-trib.rb
Thank you very much, Best Wishs

**Comment by marcosnils** [comment]
No, 

redis-trib is a command line tool that helps to manage / setup redis in many different ways. Jedis on the other hand is just a client with implements the specs proposed by redis.

redis-trib.rb is __NOT__ a redis client library, that's why it's important to understand why you don't have to mix the two things. Having said that, you can use redis-trib.rb to manage your cluster and still use JedisCluster as a client library for your app.
