### ISSUE TITLE
PubSub state not reset when resource is returned to the pool

### ISSUE THREAD

**Issue by minecrafter** [xetorthio/jedis#1176]
Relevant code: https://github.com/minecrafter/RedisBungee/blob/919c2f53c3053ffe5d41badec225c3b0dd17d352/src/main/java/com/imaginarycode/minecraft/redisbungee/RedisBungee.java#L502

It seems that when the PubSub listener fails, its resource is successfully returned to the pool, but its PubSub state is not cleared. When other code takes this resource (expecting it to be a regular Redis client), this happens:

![](https://i.imgur.com/xtkWZtm.png)

I'm using Jedis 2.7.2.

**Comment by marcosnils** [comment]
@minecrafter the current Jedis implementation doesn't know / cares if your instance is in a pubsub. We delegate to the user the responsibility to subscribe / unsubscribe because we never know when someone would like to return the instance to the pool or just keep it to do something else. 

So basically you have two alternatives

- Calling unsubscribe before returning the resource to the pool, this will make the Jedis instance reusable
- Don't use pooling for pubsub instances as it doesn't really make sense because in pubsub mode, one instance is attached to a subscription, so basically pooling doesn't make sense in this scenario.

**Comment by minecrafter** [comment]
Got it. I will make it use a dedicated non-pooled Jedis instance instead.
