### ISSUE TITLE
BinaryJedisCluster.psubscribe calls subscribe instead of psubscribe.

### ISSUE THREAD

**Issue by christophstrobl** [xetorthio/jedis#1258]
[BinaryJedisCluster.java#L1601](https://github.com/xetorthio/jedis/blob/b79d068c70a1f617f71b3eea0696aa196da9fc91/src/main/java/redis/clients/jedis/BinaryJedisCluster.java#L1601) calls _subscribe_ instead of _**p**subscribe_.

please see spring-projects/spring-session#478.

**Comment by HeartSaVioR** [comment]
@christophstrobl Thanks for noticing! I think we should have some tests around it...

**Comment by HeartSaVioR** [comment]
I think #829 is still valid.

**Comment by marcosnils** [comment]
@christophstrobl thx for reporting. It has been fixed from 2.8 onwards.

**Comment by marcosnils** [comment]
@HeartSaVioR I'm still not sure about #829. I believe this should have been spotted by reviewing the corresponding PR. 

The thing is that JedisCluster was a huge PR and difficult to review as it introduced a lot of command. I believe I prefer to fix this kind of bugs every now and then instead of writing a whole bunch of duplicated test cases just for the different strategies. 

In any case, it's just my opinion about the subject :)

**Comment by HeartSaVioR** [comment]
@marcosnils 
IMO it is really hard to find this kind of issues while reviewing without some kind of tests since we normally introduce several methods at once.

Why I treat #829 as seriously is due to its first discover. If I remember that correctly, we call `del` instead of `get` when users call `get`. We just made a mistake which can be made easily but in point of users' view it's a terrible accident regarding to use cases.
And this is over 10 times of finding a spot calling wrong method. I'd like to think about fixing it in some moment at least we find that. 

Sure we need to have a strategy of testing or specific tool to avoid writing bunch of duplicated test cases.
I don't have an concrete idea for now, but new tests just need to check that called method delegates request to proper method (same signature) so trick could be applied.
(If we can mock Jedis instance within Pipeline, Sharded, Cluster, etc we could do something with reflection and mock test.)

**Comment by marcosnils** [comment]
@HeartSaVioR if we find a nice way of implement testing then I'm ok with it. As you said, I'd like to avoid repetitive and boiler plate tests.

**Comment by HeartSaVioR** [comment]
@marcosnils Yes sure. We have hundreds of commands, so I really don't want to make hundreds * kinds of instance test methods. :)
