### ISSUE TITLE
After execute "CLIENT KILL 127.0.0.1:xxx"，jedis.isConnected is still true and jedis.isBroken is still false

### ISSUE THREAD

**Issue by lasting0001** [xetorthio/jedis#1469]
### Expected behavior

I wish jedis.isBroken is true after execute "CLIENT KILL 127.0.0.1:xxx",then it can returnBrokenResource

### Actual behavior

After execute "CLIENT KILL 127.0.0.1:xxx"，jedis.isConnected is still true and jedis.isBroken is still false

**Comment by marcosnils** [comment]
@lasting0001 that won't happen because there's no way to know that the socket connection has ended from the server side until you try to run the next command. In order for jedis to `returnBrokenResource` after connection has been killed from the server side, you need to try to run a command against the server for the socket to error out.
