### ISSUE TITLE
Send a subset of a byte array as a method

### ISSUE THREAD

**Issue by hydrogen18** [xetorthio/jedis#1478]
### Expected behavior

When using the binary redis interface, I'd like to be able to use a method like 

```
public void set(final byte[] key, final byte[] value, final int offset, final int length);
```

This would send the data starting at `value[offset]` and up to `value[offset+length]`. I could avoid some copies and allocations of `byte[]` in my code if I could do this.

### Actual behavior

A method like this does not exist

**Comment by marcosnils** [comment]
@hydrogen18 is there any other SDK that supports this?. I haven't seen this before.

**Comment by hydrogen18** [comment]
In reference to Redis and Java? I have no idea.

Java does not support slicing of an array (basically just a view of the existing data) like Go, Python, Ruby, etc.

For example, the builtin `java.io.Writer` object supports a similar method 

http://docs.oracle.com/javase/7/docs/api/java/io/Writer.html#write(char[],%20int,%20int)

The common use case is having a null-terminated byte sequence in memory, but not wanting to write the null byte.

**Comment by marcosnils** [comment]
> In reference to Redis and Java? I have no idea.

got it. I guess we would have to rethink BinaryJedis as a whole to support this. Is there a Class where this can be wrapped?.

**Comment by hydrogen18** [comment]
Yes, it would be preferred if all commands (not just set) had an overload that allowed for something like this. hset, lpush, linsert, etc.

The most generic way to support this in java would be to allow `java.io.InputStream` as an argument to commands. An input stream is just a stream of bytes.

https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html

For my example I would use make a `ByteArrayInputStream` that wraps the `byte[]` I already have.

**Comment by HeartSaVioR** [comment]
ByteBuffer could wrap it, but I'm not sure we allow duplications for whole methods to support ByteBuffer as well.

Three options here: 
1. support ByteBuffer as well and have numerous methods
2. change `byte[]` to ByteBuffer and completely break backward compatibility
3. just leave it as it is

and I'm sorry but I prefer 3 unless there're many cases which directly support ByteBuffer as parameter.

**Comment by marcosnils** [comment]
I agree with @HeartSaVioR to leave it as it is unless there's too much demand or someone puts a lot of effort in migrating the current BinaryJedis to ByteBuffer or InputStream.

**Comment by hydrogen18** [comment]
If you'd accept a pull request to add this, I should be able to work on it.

**Comment by mp911de** [comment]
Agree with @marcosnils and @HeartSaVioR. Jedis has already a whole bunch of overloads that create a lot of method signatures. `ByteBuffer` isn't trivial. Most bugs arise from non-flipped buffers (Calling `ByteBuffer.flip()` after the content was read from the buffer). `ByteBuffer` are consumed by a calling method which changes their offset and that adds another set of complexity.

Not being required to create a new array and not duplicating data is, in general, a good approach but it's something more advanced. Jedis is covering the common 80% of use cases and it's doing a pretty good job in that area.

My advice is to afford the necessary GC or use proper utilities to externalize byte array shifting when you want to stick to Jedis. If this does not work out for you, you should take a look on other Java clients (https://redis.io/clients#java) as they provide more sophisticated means to work with binary data.

On a personal note, I'd keep Jedis as-is because `ByteBuffer` is not worth the trouble. It makes things just more complicated.

**Comment by hydrogen18** [comment]
I never actually suggested using `ByteBuffer`, so I'm not really sure I understand your suggestion.

**Comment by HeartSaVioR** [comment]
@hydrogen18
You suggested adding overloaded methods which is just not acceptable. That's why I talked  alternative thing. Go figure, count how many methods BinayJedis has as is.

**Comment by marcosnils** [comment]
Jedis has always prioritized a clean and sane API. I'd love to see how other project SDK's (memcached / mongodb / whatever) deal with this problem to better understand how to help our users. 
@hydrogen18 do you know of any examples?

**Comment by matthieu-labas** [comment]
Popping into the discussion here: the proposed change is actually Java standard behavior on handling `byte[]`. E.g https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[],%20int,%20int): `read(b)` is a shortcut to `read(b, 0, b.length)`.
I agree that implementing full `InputStream` or `OutputStream` support would overcomplexify the API, but that one change would not (basically just adding those two `offset` and `length` parameters to the original methods, and add the `x(b, 0, b.length)` for backward compatibility and ease).

**Comment by marcosnils** [comment]
> , but that one change would not (basically just adding those two offset and length parameters to the original methods, and add the x(b, 0, b.length) for backward compatibility and ease).

Yes, but we'd have to rewrite all the methods. 

@matthieu-labas do you know of another client that does this? (any db / memcached / whatever)

**Comment by matthieu-labas** [comment]
@marcosnils from what I quickly read from the code, the refactoring hassle lies in the varargs used in `Protocol.sendCommand(RedisOutputStream os, ProtocolCommand command, byte[] ... args)`, which would indeed require heavy rework (probably adding an extra layer of abstraction: `Serializable` instead of `byte[]`?) so I get your point. Signatures like `sendCommand(RedisOutputStream os, ProtocolCommand command, byte[] val)` are way easier to refactor into `sendCommand(RedisOutputStream os, ProtocolCommand command, byte[] val, int off, int len)`.

As for other SDKs, I thought the JDK itself was quite a good example ;). Most network code I've worked with do that, but I don't know about the "competition".
