### ISSUE TITLE
Jedis client from pool swallows connection exceptions

### ISSUE THREAD

**Issue by kqosh** [xetorthio/jedis#1818]
### Expected behavior

When invoking Jedis.setex while the Redis server is down I would expect an exception.

### Actual behavior

It does do when it is a self created Jedis, but when I get in from the pool using getResource() is doesnt, but simply returns OK. 

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. start server
2. create or get Jedis from pool
3. invoke setex("key1", "val1"): succes
4. stop server
5. invoke setex("key2", "val2"): succes
6a. with self created Jedis: exception is thrown
6b. with Jedis from pool: no exception

### Redis / Jedis Configuration
- docker run --name some-redis -d redis
- Default: new JedisPoolConfig()

**Comment by marcosnils** [comment]
You can configure the pool to `test` the resource before retrieving it. Check the `setTestOnBorrow` property from the pool.

**Comment by kqosh** [comment]
Hi Nils,

That doesnt really fix the issue for me. I have attached a test class to
reproduce the issue. My expectation is that testNoPool and testWithPool
should behave identicaly, but they dont. TestNoPool works as expected
(reconnects gracefully so "setex 13" succeeds), but testWithPool terminates
on the "setex 12" line without any exception. I would have expected an
exception and the Jedis object should have returned to the pool as a broken
resource.

I think this may be because the pool swallows the exception because
BaseGenericObjectPool.swallowedExceptionListener is null. I cannot find how
to set my swallowedExceptionListener, it seems it is not exposed by
JedisPoolConfig nor by JedisPool.

Can you help me with this?

Regards, Ronald

**Comment by kqosh** [comment]
Here is the test class that I mentioned:
[JedisTester.java.zip](https://github.com/xetorthio/jedis/files/2098210/JedisTester.java.zip)

**Comment by smadasu** [comment]
Hello @kqosh . The thing to note here is the way direct connection throws exception and the way object pool throws exception. Both kinds are working the same way. Your is failing for "NoPool" as well. It's just that in your test class your returning a string instead of throwing the exception back in "setex". It seems like testwithNoPool is  returning gracefully. But it is not. Your setex method should look like the code below and if you do that both tests fail.
`private String setex(Jedis jedis, String key, String value) {`
        `try (Jedis j = jedis) {`
            `return j.setex(key, RETENTION_PERIOD, value);`
        `} catch (Exception ex) {`
            `throw ex;`
        `}`
    `}`

Please try this.
