### ISSUE TITLE
JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by kervin521** [xetorthio/jedis#1944]
#### Java version: 1.8.161

```xml
<dependency>
         <groupId>redis.clients</groupId>
         <artifactId>jedis</artifactId>
         <version>20161127</version>
       </dependency>
```

**Comment by kervin521** [comment]
why?

**Comment by sazzad16** [comment]
@kervin521 
1. Because of incorrect information. There isn't any version 20161127.
2. Because of incomplete information. There isn't enough information to make even a slightest sense of what's happening.
3. Because of existing issues. There are many issues with the exception, one of which may contain the solution/description/understanding already.
