### ISSUE TITLE
Jedis 2.3.x can't use on Android

### ISSUE THREAD

**Issue by xbwen** [xetorthio/jedis#538]
Jedis 2.2.x works fine on Android. But 2.3.x can't work. Because commons pool 2 use jmx and it's not supported on Android.

**Comment by esilverberg** [comment]
I can confirm that, if you stub the necessary classes, Jedis will run on Android.

**Comment by marcosnils** [comment]
@esilverberg is there a chance you can share your code so others might use Jedis on Android as well?

**Comment by esilverberg** [comment]
Strangely, while I am able to get Jedis running in my (real) Android application, when I attempt to get it working in a simple demo app I was going to upload to Github per your request, it fails every time with the note: 

```
Execution failed for task ':app:transformClassesWithDexForDebug': com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

This is because we are building a 'core library':

```
trouble processing "java/lang/management/ManagementFactory$1.class":

Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library
```

That's ok, we can get around that limitation by [amending our gradle file in this way](https://code.google.com/p/android/issues/detail?id=79280):

```
    dexOptions {
        preDexLibraries = false
    }
```
and modifying Dex task using

```
project.tasks.withType(com.android.build.gradle.tasks.Dex) {
    additionalParameters=['--core-library']
}
```

These steps, unfortunately, do not work in the demo app I have built, so I don't have anything to upload. They do work in my actual application. It appears to have something to do with the fact that the demo application includes the step, `transformClassesWithDexForDebug`, but my actual app does not. 

At this point, this has all become very android-specific and idiosyncratic and probably far afield from what your library is concerned with. I am at the limit of my knowledge of gradle and gradle's capabilities to pass parameters to specific android build steps -- sorry.
