### ISSUE TITLE
Jedis.close() should return Jedis to pool instead of closing it

### ISSUE THREAD

**Issue by secondorderpolynomial** [xetorthio/jedis#562]
What steps will reproduce the problem?
1. try (Jedis jedis = pool.getResource()) {}

What is the expected output? What do you see instead?

Jedis was accessed from a pool. Jedis should be returned to the pool. Instead the connection is closed.
This makes it impossible to use Jedis in a try-with-resource without closing it.
Also, findbugs complains if close isn't called on Jedis, as it is a Closable.

What version of the product are you using? On what operating system?

2.4.0
OS: irrelevant

Please provide any additional information below.

I think it's stylistically terse to use Jedis with a try-with-resource. This behavior would be similar to JDBC DataSource connection pooling, and I am assuming, easy enough to implement.

**Comment by tobegit3hub** [comment]
This issue is closed by won't fix. But notice that https://github.com/xetorthio/jedis/issues/909 and https://github.com/xetorthio/jedis/commit/6701b07904357dd759a11209ce98b71bd398b0fd have merged to use `close()` instead of `returnResource()` or `returnBrokenResource()` after 3.0.0-SNAPSHOT.

The latest usage is following. Make sure everybody know about that :smiley: 

```
Jedis jedis = null;
try {
  jedis = pool.getResource();
  /// ... do stuff here ... for example
  jedis.set("foo", "bar");
  String foobar = jedis.get("foo");
  jedis.zadd("sose", 0, "car"); jedis.zadd("sose", 0, "bike"); 
  Set<String> sose = jedis.zrange("sose", 0, -1);
} finally {
  if (jedis != null) {
    jedis.close();
  }
}
/// ... when closing your application:
pool.destroy();
```

**Comment by nykolaslima** [comment]
@tobegit3hub You are right. I will open a issue to fix it.

**Comment by nykolaslima** [comment]
@tobegit3hub done. You can follow it here: https://github.com/xetorthio/jedis/issues/935

**Comment by marcosnils** [comment]
@tobegit3hub I don't quite understand your comment. `Jedis.close()` now returns the resource to the pool accordingly (whether the resource is broken or not). This change has been introduced since 2.5.0 to all upcoming Jedis versions. 

returnBrokenResource and returnResource will be removed starting from 3.0 as we don't need to maintain them anymore.

**Comment by tobegit3hub** [comment]
You're right @marcosnils and I misunderstood about the feature of `Jedis.close()`. We can use `Jedis.close()` since 2.5.0 and we can't use `Pool.returnResource()` since 3.0.0.

**Comment by devesh-sh** [comment]
Hi I am very new to Jedis and trying to use it in my application.
I have created a configuration file for it which is as below.

package com.redis.config;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.CachingConfigurerSupport;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.cache.RedisCacheManager;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.connection.jedis.JedisConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.serializer.GenericToStringSerializer;
import org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer;
import org.springframework.data.redis.serializer.StringRedisSerializer;


import redis.clients.jedis.JedisPoolConfig;

@Configuration
@EnableCaching
@ComponentScan(basePackages = {"com.redhat.obpa.service.proctor"})
public class CacheConfig extends CachingConfigurerSupport {
	
	//static final JedisPoolConfig poolConfig = new JedisPoolConfig();

  @Bean
  public JedisConnectionFactory redisConnectionFactory() {
    JedisConnectionFactory redisConnectionFactory = new JedisConnectionFactory();
    
    //JedisPoolConfig poolConfig = new JedisPoolConfig();
	/*poolConfig.setMaxTotal(10);
	poolConfig.setTestOnBorrow(true);
	poolConfig.setTestOnReturn(true);*/

    // Defaults
    redisConnectionFactory.setUsePool(true);
    redisConnectionFactory.setHostName("127.0.0.1");
    redisConnectionFactory.setPort(6379);
    return redisConnectionFactory;
  }

  @Bean
  @Autowired
  public RedisTemplate<String, Proctor> redisTemplate(RedisConnectionFactory cf) {
    RedisTemplate<String, Proctor> redisTemplate = new RedisTemplate<String, Proctor>();
    redisTemplate.setConnectionFactory(cf);
    redisTemplate.setKeySerializer(new GenericToStringSerializer<>(Long.class)); 
    redisTemplate.setValueSerializer(new Jackson2JsonRedisSerializer<>(User.class)); 
    redisTemplate.afterPropertiesSet(); 
    return redisTemplate;
  }

  @Bean
  public CacheManager cacheManager(RedisTemplate redisTemplate) {
    RedisCacheManager cacheManager = new RedisCacheManager(redisTemplate);

    // Number of seconds before expiration. Defaults to unlimited (0)
    cacheManager.setDefaultExpiration(300);
    return cacheManager;
  }
  
}

I am using @cacheable with the below method signature in my service

@Cacheable(value = "user" , key = "#Id")
	public Proctor read(Long Id) throws JedisException {
		
And below is the controller I am using 

@RequestMapping(value = "/getUserDetails" , method=RequestMethod.POST, produces=MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<Proctor> getUserDetails(@RequestParam("Id") Long Id) {
		
		User user =null;
		user= userService.readUser(Id);
		user= user.updateUserDetails(user);
		return new ResponseEntity<>(user, HttpStatus.OK);
	}

I am getting the below exception at Line user= userService.readUser(Id);
Could not return the resource to the pool] with root cause 
java.lang.IllegalStateException: Invalidated object not currently part of this pool

The error occured with the first time only when hitting the url 
http://localhost:8080/myapp/getUserDetails?Id=112
However data is geting cached for each Id when the url is hit for the first time but produces the above exception. 
The exception does not occur when the frequent calls are made to the above url. 

Any help would be appreciable.
thanks in advance.

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
