### ISSUE TITLE
Resource leak in Pipeline

### ISSUE THREAD

**Issue by sertel** [xetorthio/jedis#586]
Hi,

The code in Pipeline.sync() gathers the responses of all commands buffered in this pipeline object. The getResponse() function stores these responses in a list defined in the Queable super class. Although Queable defines a clean routine, it is declared as protected and never called from the Pipeline class. 

Hence, there is no way of sweeping those responses and memory piles up.

I added this function to Pipeline in order to fix this leak:
    public void cleanResponses(){
    	if(currentMulti != null){
    		currentMulti.responses.clear();
    	}
    	super.clean();
    }

However, I'm sure you have a better approach to that.

Cheers,
Sebastian

**Comment by marcosnils** [comment]
@sertel are you still using this patch in your code? I'm not sure if we included this fix somewhere

**Comment by sertel** [comment]
I’m currently not working on a project that uses jedis. However, for the project that I worked on before, I did use that patch and it worked for me.

**Comment by marcosnils** [comment]
I don't know what the behavior was when this issue was opened but the  the `getResponses` method polls members out of the internal queue when calling `sync`. This way internal queue get's cleared on every command.

Code here: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Queable.java#L14
