### ISSUE TITLE
Why isn't there a thread safe jedis client implemented?

### ISSUE THREAD

**Issue by nachivpn** [xetorthio/jedis#812]
Is there a specific reason for not supporting thread safe jedis clients? Would this be considered if I were to draft a pull request?

**Comment by kvanapal** [comment]
Hi, I am new to this whole Redis and we are evaluating REDIS as our cache option. We are using Spring to build our applications and Spring supports Redis. The recommended client is Jedis. The RedisTemplate provided by springframework.data.redis.core can be configured to use org.springframework.data.redis.connection.jedis.JedisConnectionFactory which provides for a thread safe redisTemplate according to the documentation. This has been the standard since 1.0.0.RELEASE. 
Am I missing something here? Do I have to worry about thread safety?

Here is a link to the documentation.
[http://docs.spring.io/spring-data/redis/docs/1.0.0.RELEASE/reference/redis.html](url)
> Once configured, the template is thread-safe and can be reused across multiple instances.Out of the box, RedisTemplate uses a Java-based serializer for most of its operations. This means that any object written or read by the template will be serializer/deserialized through Java. The serialization mechanism can be easily changed on the template and the Redis module offers several implementations available in the org.springframework.data.redis.serializer package - see Section 4.6, “Serializers” for more information. Note that the template requires all keys to be non-null - values can be null as long as the underlying serializer accepts them; read the javadoc of each serializer for more information.

**Comment by HeartSaVioR** [comment]
@kvanapal That's one of attributes for Spring Data Redis, not Jedis.
