### ISSUE TITLE
Add support for auto reconneting in Jedis

### ISSUE THREAD

**Issue by costin** [xetorthio/jedis#83]
Best explained in the comments at https://jira.springsource.org/browse/DATAKV-29

**Comment by PriyankaRanjan** [comment]
Does Jedis provides this auto reconnecting / auto retry feature? if yes then how can i configure it?

**Comment by marcosnils** [comment]
@PriyankaRanjan no, because otherwise Jedis would have to queue all pending operations and retry them in a different thread until the server comes back online (or similar). Jedis returns a `JedisConnectionException` whenever the server is down or something happened in the communication. It's up to the user to decide how / when to retry the operation. You can re-use the same Jedis instance as it'll try to re-connect if a connection error has been received in the past.

The reason why we decided not to do any retry login is because usually users have different requirements for retry policies depending on their situation. That's why we encourage the community to come up with their own retry-library and open source it so others can use it.
