### ISSUE TITLE
JedisCluster or ShardedJedis can't select databases

### ISSUE THREAD

**Issue by Spectrumleeee** [xetorthio/jedis#866]
I still can't understand why Redis Cluster just offer databases 0, when user execute get/set command, all the keys will be dispatched to the specified node after calculate its slot hash, so i think i can provide a database parameter to use the specified database in the specified database just implements it by using jedis.select(database) before the jedisCluster return the jedis and execute command set. 
   This conversation has been talked about serveral times, i just need a reason to make me clear. sorry!

**Comment by marcosnils** [comment]
@Spectrumleeee regarding to Redis Cluster database support you should ask your question in the official redis group. Jedis is just a driver for redis and the same way as Redis Cluster doesn't support database selection, Jedis doesn't also.

Regarding to database selection in ShardedJedis, we've already discussed it here: https://github.com/xetorthio/jedis/pull/835. Can you provide mode details about what you don't understand and what you're suggesting to do to change that?

**Comment by nykolaslima** [comment]
@Spectrumleeee Actually with `ShardedJedis` you can select the database, see this PR https://github.com/xetorthio/jedis/pull/835

You can use `URI` to define the host and the database or you can create one `JedisShardInfo` and call the `setDb(int)` method.

This feature is labeled starting from version 2.6. @marcosnils did you guys already release it?

**Comment by HeartSaVioR** [comment]
@nykolaslima 
2.6.3 has one unmerged PR to wait for review.

Regarding decision of #835's version, seems like I made a mistake.
If we strictly apply semantic version, it should be 2.7.0 cause it doesn't resolve any bugs.
But we sometimes ignore semantic versioning because of releasing feature faster, so I don't want to revert it.

Btw, actually we're busy now to prepare Jedis 3.0.0.
If you're interested, please follow https://groups.google.com/d/msg/jedis_redis/7ZJPFp_qTY0/ISHqEPZlAnwJ.

**Comment by Spectrumleeee** [comment]
OK, thanks all, close it
