### ISSUE TITLE
jedis.keys() return type is not compatible jedis.mget() param type

### ISSUE THREAD

**Issue by myc0058** [xetorthio/jedis#876]
Set<String> keys = jedis.keys(RedisStrings.MakePostKey(userNo));
			
String[] arrayKey = keys.toArray(new String[keys.size()]); <---------- i dont want this code line
			
List<String> valueList = jedis.mget(arrayKey);

**Comment by marcosnils** [comment]
@myc0058 what do you propose?. All jedis commands that return lists / sets, etc return either `List` or `Set`, so I don't see why we need to make these to interfaces necessarily compatible.

**Comment by HeartSaVioR** [comment]
Maybe this issue is duplicated.

We already discussed about supporting vargs vs Iterable (or maybe List) to parameters.
Two things are having pros and cons, and I don't remember precisely but we decided to stick current way.

Btw, we can discuss to break current rule because we're preparing major release.

**Comment by myc0058** [comment]
my opinion is

jedis.keys() and jedis.mget() function is Jedis's functions.

Between the jedis's functions return type and param type should be match.

i want to make a overloading function 

List<String> jedis.mget(List<String> keys) {
String[] arrayKey = keys.toArray(new String[keys.size()]);
return jedis.mget(arrayKey);
}

this is just about jedis's kindness.

**Comment by marcosnils** [comment]
@myc0058 you're not proposing something generic that will solve then problem when dealing with arrays vs lists vs varargs. I don't see how we can we benefit of applying this solutions to all the other commands. Overloading the function is also something that you can do in your own project; you don't neet Jedis to provide that.

**Comment by HeartSaVioR** [comment]
Since it doesn't introduce method chaining, it is something trivial issue for us.

We're struggling to maintain SO MANY DUPLICATED methods which are just overloading methods due to support of various params. 
Personally I really wish to get rid of these, and concentrate on thinking core things.

Marcos said this earlier, which I strongly agreed.

```
Take into account that Jedis is maintained by a very few people and it get's really difficult for us to move forward unless we take some actions to boost contributions and focus on core functionality and code simplicity.
```

So sorry about it, we can reject anything if it's good to maintain Jedis easier or better whether it is convenient by user's side.

**Comment by myc0058** [comment]
thank you for answer
