### ISSUE TITLE
Interface RedisPipeline is missing eval and evalsha methods

### ISSUE THREAD

**Issue by ShahBinoy** [xetorthio/jedis#908]
Been trying to abstract my client code and discovered that eval and evalsha are not a part of Interface RedisPipeline. 

They are introduced only in PipelineBase, this breaks the the interface contract.

Thanks

**Comment by HeartSaVioR** [comment]
It's on BinaryScriptingCommandsPipeline and ScriptingCommandsPipeline.

**Comment by ShahBinoy** [comment]
I forgot to mention I am using Jedis version 2.6.2

While I see that they are declared in the two interfaces you mentioned, but the below hierarchy which is in use right now and is recommended, does not have any

(sorry, I dont know the ideal way to insert code snippets from the github repo)

abstract class PipelineBase extends Queable implements BinaryRedisPipeline, RedisPipeline {
}

I wanted to use Pipeline based client to execute lua script, but I am also gearing up for sharded Redis  3.x and want my code have minimum impact when I switch over and that's why I was looking for a standard interface to program to.

**Comment by HeartSaVioR** [comment]
Regarding code snippet, you can use ` * 3 to write block, or use gist.

Back to the issue, eval* method accepts multiple keys, which ShardedJedis doesn't support.
That's why MultiKeyPipelineBase (not PipelineBase) implement these interfaces.

Due to limitation of Redis Cluster, JedisCluster could introduce new interfaces which doesn't be shared with current interfaces.
(Please see #687 for more details.)

**Comment by ShahBinoy** [comment]
Thanks for the explanation. It does make sense now.
Seems like Jedis 3.x would be a major change. Is the Jedis 3.x going to coincide with release of Redis 3.x ?

**Comment by HeartSaVioR** [comment]
We don't planned it yet (but working on), so maybe later than Redis 3.0.

**Comment by marcosnils** [comment]
@ShahBinoy please don't forget to close the issue.

**Comment by ShahBinoy** [comment]
Thanks
