### ISSUE TITLE
JedisCluster password support

### ISSUE THREAD

**Issue by pcchan** [xetorthio/jedis#934]
JedisPool can be configured to use a password when communicating with Redis nodes, but that isn't exposed in JedisCluster as of Jedis 2.7.

**Comment by marcosnils** [comment]
@pcchan RedisCluster authentication scheme isn't defined yet (more info here: https://groups.google.com/forum/#!searchin/redis-db/password/redis-db/Z8lMxTfDct8/fQY8slgbkYYJ) that's why we haven't implemented password support so far. 

We don't want to include something that might change in the near future so for the moment we won't be adding password support to JedisCluster
