### ISSUE TITLE
Binary Jedis Return Resource

### ISSUE THREAD

**Issue by sparkpool** [xetorthio/jedis#941]
As i can see below methods are not present in jedis 2.6.2. Is there any specific reason or there is another way to release binary jedis.

public void returnBrokenResource(final BinaryJedis resource) {

returnBrokenResourceObject(resource);
}

public void returnResource(final BinaryJedis resource) {
returnResourceObject(resource);
}

This bug is resolved in #171  but it is not present in current release.

**Comment by marcosnils** [comment]
@sparkpool this was removed way back from 2.6 in this commit bbb867781deb9e8a0f073694d3ab3434426c7405 when commons-pool was introduced. 

As Jedis extends BinaryJedis you should always retrieve a `Jedis` instance from the pool and use the `close()` method finish using it. 

Documentation has been updated here: https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment

**Comment by HeartSaVioR** [comment]
@sparkpool Hey, I was finding a way to generalize JedisPool to allow BinaryJedis too, but failed cause JedisPool, JedisFactory, Pool, GenericObjectPool are tightly coupled to type and I can't find a way to generalize.
Since you can still use BinaryJedis's method signature from Jedis, I recommend you to use Jedis instead.

**Comment by sparkpool** [comment]
Thanks @marcosnils  and @HeartSaVioR

**Comment by HeartSaVioR** [comment]
@sparkpool You need to call jedis.close() to return your Jedis instance to Pool.
