### ISSUE TITLE
How to know when scan() is done?

### ISSUE THREAD

**Issue by veselov** [xetorthio/jedis#968]
Hi.

From implementation, and Redis docs, it looks like that to know if scan() is finished, one needs to compare the latest cursor to literal `0`, right?

If so, may be ScanResult can have a isLast() method that would do that?

**Comment by marcosnils** [comment]
@veselov nice observation. What about renaming the method to something like `next` so the interface can be used like the `Iterator` one. 
i.e:

```java
while (scanResult.next()) {
  //Do something
}
```

**Comment by marcosnils** [comment]
@veselov maybe we can make ScanResult implement `Iterator`? so it can be used in `foreach` loops also.

**Comment by marcosnils** [comment]
Hmmm thinking about this implementing `Iterator` wouldn't be the best thing because for the `next` method we'd have to call Jedis and do some exception handling, etc. I believe we can just provide a `hasNext()` method as @veselov originally proposed. 

@HeartSaVioR @veselov @xetorthio what do u think?

**Comment by HeartSaVioR** [comment]
For supporting various versions of Redis, Jedis didn't evaluate return value to determine sth. .
I'm not 100% sure that antirez never changes representation of "end of scan".
If we're sure, we can just go on. Actually it's better to have it.

**Comment by veselov** [comment]
I am all for making ScanResult return an iterator, and even stream for 1.8, as a utility mechanism. The caveat will be that the next(), or the stream producer may throw an exception. Which, as long as the implementation is ready for, can be handled. On the low level, just having a hasMore()/scanFinished() method is sufficient to prevent the Jedis user to having to have Redis knowledge on how to do determine if the scan is finished.

**Comment by allanwax** [comment]
When the scan returns an index of `0` it is done

**Comment by HeartSaVioR** [comment]
We know about that, but if Jedis has to know about that, and when antirez changes value for end of scan, next Jedis version couldn't be compatible with previous version. We were trying our best to avoid it.

**Comment by veselov** [comment]
I agree with @HeartSaVioR point, but wouldn't that be tantamount to changing the protocol? Changing `cursor==0` condition is no different than changing any other contract Redis has, but Jedis does depend on other contracts.

**Comment by HeartSaVioR** [comment]
http://redis.io/commands/ttl
You can see that return values are changed once. (Added -2)
I don't think it shouldn't be occurred again, but who knows.

**Comment by corydolphin** [comment]
Hi all, awesome discussion here! I think there are some great ideas here.

Currently Scan does not throw any checked exceptions, which I believe would allow a naive wrapper around it to be compatible at an API level, without hiding any exception handling. This seems like it would be compatible with jedis from a checked-exception point of view.

Alternatively, a more incremental, but perhaps less beautiful patch could be to:
1. Make a new `scan(ScanParams scanParams` which initializes the cursor to `0`
2. Change ScanResult to have a `hasNext()` and `ScanResult fetchNext(Jedis j)`

Thoughts? Would love to help out on this, since it took a little bit of back and forth between the Redis documentation and Jedis to understand what to do here.

**Comment by allanwax** [comment]
Perhaps just having next is sufficient.  The fragment below is similar to BufferedReader.readline().

```java
ScanParams params = new ScanParams().match(match).count(100);
...
results = jedis.scan(scanMarker, params);
...
String result = null;
while ((result = results.next()) != null) {
   ... do something ...
}
```

next() would handle checking the marker and issuing another scan as needed until the a marker of `0` is reached.  This abstracts out the underlying knowledge and if scan changes in the future, there should be little impact.  

It would also handle the case where a particular scan in a series of scans (before the '0' marker is reached) returns no results for a particular scan but the marker is non-zero, indicating the scan succeeded, but try some more.

**Comment by HeartSaVioR** [comment]
@veselov @corydolphin @allanwax @marcosnils 
As @veselov pointed out, the main point is that next() should call jedis.scan() again, and it could incur any types of Exception which should be handled, especially JedisConnectionException. In other words, handling broken connection is the main point.

So easiest and safest (in Jedis's point of view) way is just providing hasNext(), as @veselov stated to let users know whether scan iteration is end or not.
After that users doesn't have to know the marker '0'.

Additional idea is passing ScanResult to scan() method, which can force users to call scan() with handling Exception, but users doesn't have to handle cursor value themselves.

Btw, I'm wondering that Redis could change its return value. (I saw similar things several times!)
But at the same time, I think he can't change the value ```end of scan``` since it can break whole users codes.
So, now I'm sure we can take 0 as constant value of ```end of scan```.

**Comment by allanwax** [comment]
I still think patterning `next()` like `BufferedReader.readLine` is a simpler way to go.  Under the hood it would call `scan()` as many times as needed, throw an exception as needed, and remove the need for the user to know about the magic marker 0.  People are used to the BufferedReader pattern so it would be natural and very compact to write (example above).

What I don't see mentioned in this discussion is resource handling.  If we're doing stuff under the hood there needs to be a way to say 'stop' in the middle of scanning (not real time) and clean up resources.  Perhaps we need some like `done()` or some other name to invalidate everything and release associated resources with the scan.  A not as good solution would be to add `finalize()` to the class and depend on it but adding finalize() as a guard to make sure that _eventually_ the resources get released is probably a good idea but with *no* guarantee that it will ever be executed.

**Comment by sazzad16** [comment]
#1458 resolves this by `ScanResult.isCompleteIteration()`
