### ISSUE TITLE
Make deprecated JedisPool code a wrapper for new 3.0 code

### ISSUE THREAD

**Issue by allanwax** [xetorthio/jedis#979]
If we're moving to use close() as the release of resources, let's make it do that now

```java
public void returnResource(final Jedis resource) {
    if (resource != null) {
      try {
        resource.resetState();
        returnResourceObject(resource);
      } catch (Exception e) {
        returnBrokenResource(resource);
        throw new JedisException("Could not return the resource to the pool", e);
      }
    }
  }
```

change to 

```java
public void returnResource(final Jedis resource) {
    if (resource != null) {
      resource.close();
    }
  }
```

etc.

**Comment by marcosnils** [comment]
@allanwax we already changed `JedisPool.returnResource` to package protected.  Another thing is that `jedis.close()` calls `JedisPool.returnResource` so the change you're proposing will end up in an infinite recursive call.

**Comment by allanwax** [comment]
Why is new code calling deprecated code?  If it is going to disappear in 3.0 as the comments says, what's it going to call then?  What happens if someone gets a JedisPool resource now and causes close() to close it?

**Comment by marcosnils** [comment]
@allanwax we flagged deprecated just for 2.6 and 2.7 versions which we couldn't remove due to backwards compatibility. In 3.0 `returnResource and returnBrokenResource` are package protected to JedisPool so users now should close a jedis connection using `jedis.close()` only. 

When we said that it was going to disappear in 3.0 we were referring to that those functions will not be public, but we never intended to remove them.

**Comment by marcosnils** [comment]
> What happens if someone gets a JedisPool resource now and calls close() to close it?

Internally we will call `returnResource` or `returnBrokenResource` depending on the resource state which is something we're checking instead of delegating that responsibility to the user.

**Comment by allanwax** [comment]
Good for now.

**Comment by marcosnils** [comment]
@allanwax can you close the issue?
